name: fortlev_delivery
description: Fortlev Delivery Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  url_launcher: ^5.4.2
  local_auth: ^0.6.1+3
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  camera:
  path_provider:
  uuid: ^2.0.4
  image_crop: ^0.3.2
  google_maps_flutter: ^0.5.11
  dio: ^3.0.9
  geolocator: ^5.3.1
  intl:
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:

flutter:
  uses-material-design: true
